### ISSUE TITLE
Google maps urls are to long for the DB field

### ISSUE THREAD

**Issue by wiegerjelsma** [elivz/VzUrl-Craft#10]
It seems that the field cannot handle iFrame source urls to embed Google Maps onto a webpage. That type of URLs are to long.

**Comment by elivz** [comment]
Can you give me an example of a URL that doesn't work for you? I just tried a couple from GMaps and didn't have any problems with them. Also, are you seeing an error, or is it just marking them as invalid?

**Comment by elivz** [comment]
Hang on, I just realized you are talking about the database character limit (should have read the title of your post more closely, instead of focusing on the text....). There is a 255-charcter limit by default, but I can increase that in the next release. I'll try to get that out in the next day or two!

**Comment by wiegerjelsma** [comment]
Ah ok! Great!

**Comment by elivz** [comment]
I just released [version 1.0.4](https://github.com/elivz/VzUrl-Craft/archive/1.0.4.zip), which increases the maximum number of characters in the database column to 2000.
