### ISSUE TITLE
Asynchronous validation?

### ISSUE THREAD

**Issue by lindseydiloreto** [elivz/VzUrl-Craft#4]
First of all, I love this plugin! It does exactly what it says, and it does it well. :)

This is probably a major feature request, so I'd love to hear your thoughts on it. Is it possible to have the URLs be validated via **asynchronous** AJAX?

I've got a page with several URL fields, and every time I visit the page, every field takes time to validate. But the real bummer is that _Craft is locked up while those requests are happening._ I can't even navigate away to another page... I need to sit and wait from them to all validate. :(

![Validating URLs...](https://cloud.githubusercontent.com/assets/5309692/8463520/c3de114c-1fef-11e5-9d51-3be0e4f845f7.png)

It's a real pain on days like today... I'm working at a coffee shop and the internet is terribly slow.

Thanks for looking into this, let me know what you think!

**Comment by elivz** [comment]
Interesting... I will definitely look into that. I am using Craft's AJAX helper function, so unless that is somehow triggering a synchronous call, I suspect something else may be going on. I'll let you know what I find!

**Comment by lindseydiloreto** [comment]
Awesome! Thanks for looking into that. :)

**Comment by elivz** [comment]
Lindsey,

Would you mind telling me what browser you were seeing that in? I've just been looking into this, and when I test it, all the fields get checked simultaneously (have tried in Safari and FF so far). I'll keep working on it, but I and just trying to narrow down what might be different between your set up and mine...

**Comment by lindseydiloreto** [comment]
Hey Eli,

This is in Chrome (43.0.2357) on a Mac (10.8). Strange that it's working in other browsers, I didn't even think that it could be a browser issue!

I appreciate you investigating... let me know if you have any other questions!

**Comment by elivz** [comment]
I don't think it is a browser issue after all. I'm still trying to figure out exactly what is going on. Part of it just comes down to the response time from the domain we're checking - if the remote server takes a couple seconds to respond, there's not much we can do about it. 

But it also seems almost like PHP itself might be putting the requests into some kind of queue. I don't know why it would - since they are each in their own request/thread - but it looks like the the proxy responses from the local server always come back staggered, even though they go out at the same time. Mysterious!

<img width="750" alt="screen shot 2015-07-06 at 10 14 15 pm" src="https://cloud.githubusercontent.com/assets/62592/8539142/6901f84c-242c-11e5-9375-d19cfa56040e.png">

I'll keep working on it tomorrow, and let you know if I find a solution.

**Comment by lindseydiloreto** [comment]
That is super weird!

Since ServerPilot makes it really easy to switch between PHP versions, I just tested it out in 5.4, 5.5, and 5.6... they're all having the same issue (on Chrome)

Based on your experience, I also just tested on Safari & Firefox. On the surface, neither seemed to be waiting for the processes to finish. (The spinning graphics were still spinning when the page changed.) But in reality, it seemed like it was still taking a long time to navigate to the next page... about as long as it takes for all of those processes to finish.

Hope that helps. If you don't figure it out tomorrow, then don't worry about it. It's certainly a nuisance, but not a total showstopper for me.

**Comment by SublymeRick** [comment]
Has any progress been made on this?

**Comment by elivz** [comment]
Not really, unfortunately. It appears that PHP (at least in its default configuration) writes to a lock file when you start the session, and won't let the next request from the same user begin processing until that lock is released. I'm not sure there is a workaround for that, or at least I was never able to find one. I will give it another look when I have a chance, in case anything new occurs to me to try.....

**Comment by SublymeRick** [comment]
Im not too sure how plugins are programmed yet, but couldnt you use jquery / ajax to check the link client side, instead of doing it with php?

**Comment by elivz** [comment]
If only! Unfortunately you can't perform AJAX requests to a different domain (at least without prior setup on the remote server). That is a fundamental restriction of AJAX in the browser, so the only way to get around it is to proxy the request through a PHP script on the server.

**Comment by elivz** [comment]
Version 1.1, which I published over the weekend, should fix this for you. It now queues up the validation requests to does them one after another rather than all at once. That means it will take longer to validate all the URLs on the page, of course, but prevents it from exhausting the browser's connection limit or hammering the server too hard. Let me know if you see any more similar problems!

**Comment by lindseydiloreto** [comment]
Fantastic, thanks @elivz!

I haven't tried the new version yet, but I'll make sure to report back when I do. 👍
