### ISSUE TITLE
Instagram url fails validation

### ISSUE THREAD

**Issue by shunluoifong** [elivz/VzUrl-Craft#8]
When I enter an Instagram URL like http://www.instagram.com/shunluoifong, I get an invalid error. If I put in just the base Instagram url, https://www.instagram.com/, it works fine. Bug?

**Comment by SherriAlexander** [comment]
I'm seeing this same behavior as well.

**Comment by SherriAlexander** [comment]
If it helps with troubleshooting, when I inserted some console.log statements into input.js, I found that the http_code returned for an Instagram URL is 0.  

I've also noticed that LinkedIn URLs are failing validation, but those are failing with a http_code 999 error (seems to be due to blocking/throttling efforts by LinkedIn), so that's definitely a separate issue.

**Comment by elivz** [comment]
I made a few changes to the validation system, and this appears to be fixed now. That Instagram URL you mentioned validates (well, it actually shows the redirect to the "https" version, which is marked as valid). Let me know if you see any more similar issues.
